#!/usr/bin/env ruby
require 'yaml'

system("pwd")

rails_env = "production"
file = "current/config/database.yml"
begin
  config = YAML::load(File.open(file))
  adapter = config[rails_env]["adapter"]
  database = config[rails_env]["database"]
  db_username = config[rails_env]["username"]
  db_password = config[rails_env]["password"]
  timestamp = Time.new.to_i.to_s
  file_name = "#{database}-#{timestamp}.sql"


rescue Errno::ENOENT
  puts "No such file or directory #{file}"
end
