#!/bin/sh

if [ `id -u` = 0 ]; then 
 echo "rcasts launched by root, will exit now"
 echo "please launch as normal user"
 exit 0
fi

URL="https://raw.github.com/4freaks/Utilites/master"

  if [ "$1" = "" ]; then
    echo "rcasts need parameter"
elif  [ "$1" = "upgrade" ]; then
  sudo wget -Nq $URL/rcasts -O /usr/bin/rcasts && sudo chmod +x /usr/bin/rcasts
  exit 0
elif  [ "$1" = "help" ]; then
  curl -s $URL/README
elif  [ "$1" = "rcstyle" ]; then
  wget -Nq $URL/rbeautify.rb -O /usr/bin/rcstyle && chmod +x /usr/bin/rcstyle && echo "rcstyle installed, now you can run it with rcstyle file.rb"
elif  [ "$1" = "style.rb" ]; then
  wget -Nq $URL/rbeautify.rb -O temp_style_script.rb && chmod +x temp_style_script.rb
  find . -type f -iname "*.rb" -exec ./temp_style_script.rb {} \;
  rm temp_style_script.rb
else
    cd /tmp && wget -Nq $URL/$1 && chmod +x $1
    ./$1
    rm $1
fi
