#!/bin/sh

if [ `id -u` = 0 ]; then 
 echo "rcasts launched by root, will exit now"
 echo "please launch as normal user"
 exit 0
fi

URL="https://raw.github.com/4freaks/Utilites/master"

cd /tmp

  if [ "$1" = "" ]; then
    echo "rcasts need parameter"
elif  [ "$1" = "upgrade" ]; then
  cd /usr/bin/ && sudo wget -Nq $URL/rcasts && chmod +x rcasts
  exit 0
elif  [ "$1" = "help" ]; then
  curl -s $URL/README
elif  [ "$1" = "rcstyle" ]; then
  wget -Nq $URL/rbeautify.rb && sudo mv rbeautify.rb /usr/bin/rcstyle && chmod +x /usr/bin/rcstyle && echo "rcstyle installed, now you can run it with rcstyle file.rb"
else
    wget -Nq $URL/$1
    chmod +x $1
    ./$1
    rm $1
fi
