#!/usr/bin/env ruby
def gem_available?(name)
  Gem::Specification.find_by_name(name)
rescue Gem::LoadError
  false
rescue
  Gem.available?(name)
end

unless gem_available?("colorize")
  puts "Please install gem colorize first:"
  puts "gem install colorize"
  exit
end
require 'colorize'
require 'net/http'
require 'uri'


sites = %w{google.com booq.pro railscasts.ru ip.railscasts.ru q3.railscasts.ru ansever.booq.pro yandex.ru}
sites.map!{|s| "http://" + s}

def get_codes(array)
  result = []
  threads = []
  array.each do |url|
    threads << Thread.new do
      uri = URI.parse(url)
      t1 = Time.new
      resp = Net::HTTP.get_response(uri)
      t2 = Time.new
      print "."
      Thread.current["myhash"] = {:site => url, :code => resp.code, :time => t2-t1}
    end
  end
  threads.each {|t| t.join; result << t["myhash"]} 
  return result
end

print "Processing (#{sites.length} threads) "
sites = get_codes(sites).sort{|x,y| x[:code].to_i <=> y[:code].to_i}
puts " done"

sites.each do |hash|
  code = hash[:code]
  site = hash[:site]
  case
  when code == "200" || code[0] == "3"
    message = "[OK]".colorize( :light_green )
  when code[0] == '5'
    message = "[FAIL]".colorize( :light_red )
    fail = true
  else
    message = "[#{code}]".colorize( :light_yellow )
  end
  puts "#{message}\t:\t#{(fail)? site.colorize( :light_red ) : site.colorize( :white )}"
end
